services:
  db:
    image: postgres:17
    container_name: tech-chall
    environment:
      POSTGRES_DB: tech-chall
      POSTGRES_USER: tech-chall
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"